package server_test

import (
	"context"
	"net"
	"net/netip"
	"strconv"
	"testing"
	"time"

	"github.com/k0ngk0ng/wire-connect/internal/server"
	"github.com/k0ngk0ng/wire-connect/internal/transport"
	"github.com/pion/ice/v4"
	"github.com/pion/stun/v4"
	tailscalestun "tailscale.com/net/stun"
)

func TestServeSTUNAcceptsPionAndTailscaleRequests(t *testing.T) {
	pc := startSTUNServer(t)
	client, err := net.ListenPacket("udp4", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer client.Close()

	serverAddr := pc.LocalAddr()

	// This is a minimal request generated by a standard ICE client. It has no
	// SOFTWARE or FINGERPRINT attribute; neither is required by RFC 5389.
	pionRequest := stun.MustBuild(stun.TransactionID, stun.BindingRequest)
	if pionRequest.Contains(stun.AttrSoftware) {
		t.Fatal("Pion request unexpectedly contains SOFTWARE")
	}
	if pionRequest.Contains(stun.AttrFingerprint) {
		t.Fatal("minimal request unexpectedly contains FINGERPRINT")
	}
	if _, err := client.WriteTo(pionRequest.Raw, serverAddr); err != nil {
		t.Fatal(err)
	}
	pionResponse := readSTUNResponse(t, client, pionRequest.TransactionID)
	if pionResponse.Type != stun.BindingSuccess {
		t.Fatalf("Pion response type = %s, want %s", pionResponse.Type, stun.BindingSuccess)
	}
	var pionMapped stun.XORMappedAddress
	if err := pionMapped.GetFrom(pionResponse); err != nil {
		t.Fatalf("decode Pion XOR-MAPPED-ADDRESS: %v", err)
	}
	assertMappedAddress(t, client, pionMapped)

	// Keep the legacy Tailscale request format working for existing clients.
	tailscaleID := tailscalestun.NewTxID()
	if _, err := client.WriteTo(tailscalestun.Request(tailscaleID), serverAddr); err != nil {
		t.Fatal(err)
	}
	responseBuf := make([]byte, 2048)
	if err := client.SetReadDeadline(time.Now().Add(time.Second)); err != nil {
		t.Fatal(err)
	}
	n, _, err := client.ReadFrom(responseBuf)
	if err != nil {
		t.Fatalf("read Tailscale response: %v", err)
	}
	gotID, gotAddr, err := tailscalestun.ParseResponse(responseBuf[:n])
	if err != nil {
		t.Fatalf("parse Tailscale response: %v", err)
	}
	if gotID != tailscaleID {
		t.Fatalf("Tailscale response transaction ID = %x, want %x", gotID, tailscaleID)
	}
	assertMappedAddrPort(t, client, gotAddr)

}

func TestServeSTUNIgnoresMalformedAndNonBindingThenRecovers(t *testing.T) {
	pc := startSTUNServer(t)
	client, err := net.ListenPacket("udp4", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer client.Close()

	serverAddr := pc.LocalAddr()
	if _, err := client.WriteTo([]byte{0x00, 0x01, 0x00}, serverAddr); err != nil {
		t.Fatal(err)
	}
	nonBinding := stun.MustBuild(stun.TransactionID, stun.NewType(stun.MethodBinding, stun.ClassIndication), stun.Fingerprint)
	if _, err := client.WriteTo(nonBinding.Raw, serverAddr); err != nil {
		t.Fatal(err)
	}

	good := stun.MustBuild(stun.TransactionID, stun.BindingRequest, stun.Fingerprint)
	if _, err := client.WriteTo(good.Raw, serverAddr); err != nil {
		t.Fatal(err)
	}
	response := readSTUNResponse(t, client, good.TransactionID)
	if response.Type != stun.BindingSuccess {
		t.Fatalf("recovery response type = %s, want %s", response.Type, stun.BindingSuccess)
	}
}

func TestServeSTUNProvidesServerReflexiveCandidate(t *testing.T) {
	pc := startSTUNServer(t)
	addr, ok := pc.LocalAddr().(*net.UDPAddr)
	if !ok {
		t.Fatalf("STUN listener address type = %T, want *net.UDPAddr", pc.LocalAddr())
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	iceAgent, err := transport.NewICE(ctx, "stun:"+net.JoinHostPort("127.0.0.1", strconv.Itoa(addr.Port)), true)
	if err != nil {
		t.Fatal(err)
	}
	defer iceAgent.Close()

	offer, err := iceAgent.LocalOffer(ctx)
	if err != nil {
		t.Fatalf("gather ICE offer: %v", err)
	}
	for _, raw := range offer.Candidates {
		candidate, err := ice.UnmarshalCandidate(raw)
		if err != nil {
			t.Fatalf("decode ICE candidate %q: %v", raw, err)
		}
		if candidate.Type() == ice.CandidateTypeServerReflexive {
			return
		}
	}
	t.Fatalf("ICE offer has no server-reflexive candidate: %v", offer.Candidates)
}

func startSTUNServer(t *testing.T) net.PacketConn {
	t.Helper()
	pc, err := net.ListenPacket("udp4", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() {
		done <- server.ServeSTUN(ctx, pc)
	}()
	t.Cleanup(func() {
		cancel()
		_ = pc.Close()
		select {
		case err := <-done:
			if err != nil {
				t.Errorf("ServeSTUN: %v", err)
			}
		case <-time.After(time.Second):
			t.Error("ServeSTUN did not stop during cleanup")
		}
	})
	return pc
}

func readSTUNResponse(t *testing.T, pc net.PacketConn, transactionID [stun.TransactionIDSize]byte) *stun.Message {
	t.Helper()
	if err := pc.SetReadDeadline(time.Now().Add(time.Second)); err != nil {
		t.Fatal(err)
	}
	buf := make([]byte, 2048)
	n, _, err := pc.ReadFrom(buf)
	if err != nil {
		t.Fatalf("read STUN response: %v", err)
	}
	response := stun.New()
	if err := stun.Decode(buf[:n], response); err != nil {
		t.Fatalf("decode STUN response: %v", err)
	}
	if response.TransactionID != transactionID {
		t.Fatalf("STUN response transaction ID = %x, want %x", response.TransactionID, transactionID)
	}
	return response
}

func assertMappedAddress(t *testing.T, client net.PacketConn, mapped stun.XORMappedAddress) {
	t.Helper()
	assertMappedAddrPort(t, client, netip.AddrPortFrom(netip.MustParseAddr(mapped.IP.String()), uint16(mapped.Port)))
}

func assertMappedAddrPort(t *testing.T, client net.PacketConn, got netip.AddrPort) {
	t.Helper()
	wantAddr, ok := client.LocalAddr().(*net.UDPAddr)
	if !ok {
		t.Fatalf("client address type = %T, want *net.UDPAddr", client.LocalAddr())
	}
	want := wantAddr.AddrPort()
	if got.Port() != want.Port() || got.Addr().Unmap() != want.Addr().Unmap() {
		t.Fatalf("mapped address = %s, want %s", got, want)
	}
}
